name: Fix linting from a comment
jobs:
  fix-linting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd
    - name: GARALT debug probe
      run: 'printf "GARALT_DBG: PR number is %s\n" "${{ github.event.issue.number }}"'
      continue-on-error: true
    - name: Checkout Pull Request
      run: gh pr checkout ${{ github.event.issue.number }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c
      with:
        python-version: '3.12'
    - name: Install pre-commit
      run: pip install pre-commit
    - name: GARALT debug probe
      run: |-
        printf "GARALT_DBG: .pre-commit-config.yaml content:\n"
        if [ -f .pre-commit-config.yaml ]; then
          cat .pre-commit-config.yaml
        else
          echo "File not found"
        fi
      continue-on-error: true
    - name: Run pre-commit
      id: pre-commit
      run: pre-commit run --all-files
      continue-on-error: true
env:
  GARALT_SECRET: ${{ secrets.GARALT }}
on:
  issue_comment:
    types:
    - created
